### ISSUE TITLE
farm_function.js Cleanup

### ISSUE THREAD

**Issue by TheGoo-ooo** [HE-Arc/Beer-Empire#19]
This file does what it is supposed to do but it's a mess. It has already been modified on the advices of Jesus (using data-... to transmit data). Read the TODOs to fix it. This issue is a memento for me or anyone replacing me if I were to die tomorrow. Just don't do it if there's still something more important to be done. 

It ain't hard but it takes time.

**Comment by greut** [comment]
https://www.youtube.com/watch?v=R2_Mn-qRKjA keep up!
